# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HearchIndexEntry.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "com.stupidbeauty.hearch.HearchIndexEntry" do
    optional :keyword, :string, 1
    repeated :articleId, :int32, 2
  end
end

module Com
  module Stupidbeauty
    module Hearch
      HearchIndexEntry = Google::Protobuf::DescriptorPool.generated_pool.lookup("com.stupidbeauty.hearch.HearchIndexEntry").msgclass
    end
  end
end
